import { useNavigate } from 'react-router-dom';
import { ArrowButton, CARD, Section, SectionHeader } from '../Section';

type Level = 'deficit' | 'developing' | 'mastery';

const COLUMNS = ['Design', 'Engineering', 'Product', 'Marketing'] as const;

const ROWS: readonly { axis: string; cells: readonly number[] }[] = [
  { axis: 'Strategy', cells: [78, 84, 91, 64] },
  { axis: 'Technical Skills', cells: [88, 94, 72, 68] },
  { axis: 'Research & Discovery', cells: [92, 58, 85, 76] },
  { axis: 'Execution Speed', cells: [85, 89, 79, 86] },
];

const levelOf = (value: number): Level =>
  value < 65 ? 'deficit' : value >= 90 ? 'mastery' : 'developing';

const CELL: Record<Level, string> = {
  deficit: 'bg-[#fbd9d6] text-[#b42318]',
  developing: 'bg-[#e0e3fb] text-[#3525cd]',
  mastery: 'bg-[#4f46e5] text-white',
};

const STEPS = [
  {
    title: 'Assess',
    text: 'Deploy role-specific evaluations calibrated to actual day-to-day deliverables.',
  },
  {
    title: 'Identify',
    text: 'Spot critical blindspots across business units before execution breakdowns occur.',
  },
  {
    title: 'Benchmark',
    text: 'Compare internal capability against industry standards and high-performing cohorts.',
  },
  {
    title: 'Develop',
    text: 'Provide managers with targeted modular roadmaps for individuals and pods.',
  },
  {
    title: 'Measure',
    text: 'Retest quarterly to demonstrate quantified ROI on training and team capability gains.',
  },
] as const;

export const Workforce = () => {
  const navigate = useNavigate();

  return (
    <Section id="workforce" bg="bg-white">
      <SectionHeader
        eyebrow="Workforce Capability Intelligence"
        title="Know what your team can actually do."
        lead="CareerLine AI helps organizations assess employees according to the roles they actually perform—not simply the titles they hold. Uncover systemic blind spots before they impact product releases."
      />

      <div className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,6fr)_minmax(0,4.5fr)] lg:items-end lg:gap-10">
        <div className={`p-5 sm:p-6 ${CARD}`}>
          <div className="flex flex-wrap items-start justify-between gap-2">
            <div>
              <h3 className="font-heading text-[15px] font-semibold text-[#141b34]">
                Engineering &amp; Product Capability Matrix
              </h3>
              <p className="mt-0.5 text-[10.5px] text-[#5a6270]">
                Aggregated across 42 active team members
              </p>
            </div>
            <span className="rounded-full bg-[#e8eaff] px-3 py-1 text-[10.5px] font-medium text-[#464555]">
              Cohort Q2
            </span>
          </div>

          <div className="mt-5 overflow-x-auto">
            <table className="w-full min-w-110 border-separate border-spacing-y-1.5 text-[11px]">
              <thead>
                <tr className="text-[10.5px] font-semibold text-[#464555]">
                  <th className="pb-1 text-left font-semibold">Competency Axis</th>
                  {COLUMNS.map((col) => (
                    <th key={col} className="pb-1 text-center font-semibold">
                      {col}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {ROWS.map(({ axis, cells }) => (
                  <tr key={axis}>
                    <th
                      scope="row"
                      className="pr-2 text-left text-[11px] font-semibold text-[#141b34]"
                    >
                      {axis}
                    </th>
                    {cells.map((value, i) => (
                      <td key={COLUMNS[i]} className="px-0.5">
                        <div
                          className={`rounded-md py-2 text-center text-[11px] font-semibold ${CELL[levelOf(value)]}`}
                        >
                          {value}%
                        </div>
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="mt-4 flex flex-wrap items-center justify-between gap-2 text-[10px] text-[#5a6270]">
            <div className="flex flex-wrap items-center gap-4">
              <span className="flex items-center gap-1.5">
                <span className="h-2.5 w-2.5 rounded-sm bg-[#fbd9d6]" /> &lt;65% Deficit
              </span>
              <span className="flex items-center gap-1.5">
                <span className="h-2.5 w-2.5 rounded-sm bg-[#e0e3fb]" /> 65-80% Developing
              </span>
              <span className="flex items-center gap-1.5">
                <span className="h-2.5 w-2.5 rounded-sm bg-[#4f46e5]" /> 80%+ Mastery
              </span>
            </div>
            <span>Auto-generated by CareerLine Org API</span>
          </div>
        </div>

        <div>
          <ol className="flex flex-col gap-4">
            {STEPS.map(({ title, text }, i) => (
              <li key={title} className="flex items-start gap-3">
                <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#e4e2ff] text-[11px] font-semibold text-[#3525cd]">
                  {i + 1}
                </span>
                <div>
                  <p className="font-heading text-[13.5px] font-semibold text-[#141b34]">{title}</p>
                  <p className="mt-0.5 text-[11.5px] leading-relaxed text-[#5a6270]">{text}</p>
                </div>
              </li>
            ))}
          </ol>

          <div className="mt-6 flex flex-wrap gap-2">
            <ArrowButton variant="solid" onClick={() => navigate('/organization/sign-up')}>
              Assess Your Team
            </ArrowButton>
            <button
              type="button"
              onClick={() => navigate('/contact')}
              className="h-11 rounded-lg bg-[#e8eaff] px-5 text-[13px] font-medium text-[#1f2a44] transition-colors hover:bg-[#dcdffc]"
            >
              Request Enterprise Demo
            </button>
          </div>
        </div>
      </div>
    </Section>
  );
};
